In [1]:
import numpy as np
import pandas as pd

In [2]:
import tensorflow as tf

In [5]:
print(tf.version)

<module 'tensorflow._api.v2.version' from '/home/kar/.local/lib/python3.8/site-packages/tensorflow/_api/v2/version/__init__.py'>


In [6]:
f=tf.Variable(["dasd","gfdgfg"],tf.string)

### must be a squared tensor no other shape is allowed of lowest rank 2

In [24]:
x=tf.Variable([[1,2,3],[4,5,6]],tf.int8)

In [17]:
tf.rank(x)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [23]:
x.shape

TensorShape([2, 3])

In [25]:
x

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [26]:
tf.reshape(x,[3,2])

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [32]:
d=tf.ones([2,2,10],tf.int8)

In [33]:
tf.reshape(d,[40])

<tf.Tensor: shape=(40,), dtype=int8, numpy=
array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int8)>

## linear regg

In [3]:
import sklearn as sk

In [4]:
df=pd.read_csv("data/titanic_train.csv")
test=pd.read_csv("data/titanic_test.csv")
xt=pd.read_csv("data/titanic/results-rf.csv")
test=pd.concat([test,xt])
y_train=df.pop('Survived')
y_test=xt['Survived']

In [50]:
df["Survived"]

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64

In [5]:
test.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 836 entries, 0 to 417
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  836 non-null    int64  
 1   Pclass       418 non-null    float64
 2   Name         418 non-null    object 
 3   Sex          418 non-null    object 
 4   Age          332 non-null    float64
 5   SibSp        418 non-null    float64
 6   Parch        418 non-null    float64
 7   Ticket       418 non-null    object 
 8   Fare         417 non-null    float64
 9   Cabin        91 non-null     object 
 10  Embarked     418 non-null    object 
 11  Survived     418 non-null    float64
dtypes: float64(6), int64(1), object(5)
memory usage: 84.9+ KB


In [12]:
df.head()

PassengerId  Pclass                                               Name  \
0            1       3                            Braund, Mr. Owen Harris   
1            2       1  Cumings, Mrs. John Bradley (Florence Briggs Th...   
2            3       3                             Heikkinen, Miss. Laina   
3            4       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)   
4            5       3                           Allen, Mr. William Henry   

      Sex   Age  SibSp  Parch            Ticket     Fare Cabin Embarked  
0    male  22.0      1      0         A/5 21171   7.2500   NaN        S  
1  female  38.0      1      0          PC 17599  71.2833   C85        C  
2  female  26.0      0      0  STON/O2. 3101282   7.9250   NaN        S  
3  female  35.0      1      0            113803  53.1000  C123        S  
4    male  35.0      0      0            373450   8.0500   NaN        S

In [16]:
tf.estimator.

array(['male', 'female'], dtype=object)