In [ ]:
#Step1: import all the liabraries
#step2: load the datset 
#step3:  you have to divide datset into 2 parts : dependent variable and independent 
# step 4: you have to check nanvalues and categorial column in independent variable
# step 5: if nan values present in the datset :to remove nan values you have to use simple imputer/ fillna
#if categorial column present in datset : you have to create dumies/ LabelEncoder/ Onehotencoding
#Step 6: diveide datset into training and testing part: divide into 4 parts(xtrain,xtest,ytrain,ytest)
#step 7 : import algorithm you want to use to give training to the model
# Step8:to give training to model i have to use fit(xtrain,ytrain)
# Step9:to predict the category of  unseen values: use predict(xtest)
# Step10:to do model evalution : accuracyscore (ytest,prediction)




In [ ]:
i=df

In [1]:
import pandas as pd
import numpy as np


In [4]:
df= pd.read_csv("Iris.csv")
df.head(1)

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa

In [6]:
i=df.iloc[:,1:5]
d=df.iloc[:,5]
d

0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...      
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: Species, Length: 150, dtype: object

In [8]:
# to check nan values
i.isnull().sum()
# to check categorial column 
i.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   SepalLengthCm  150 non-null    float64
 1   SepalWidthCm   150 non-null    float64
 2   PetalLengthCm  150 non-null    float64
 3   PetalWidthCm   150 non-null    float64
dtypes: float64(4)
memory usage: 4.8 KB


In [14]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split (i, d, test_size = 0.20,random_state = 0)

X_test

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
114            5.8           2.8            5.1           2.4
62             6.0           2.2            4.0           1.0
33             5.5           4.2            1.4           0.2
107            7.3           2.9            6.3           1.8
7              5.0           3.4            1.5           0.2
100            6.3           3.3            6.0           2.5
40             5.0           3.5            1.3           0.3
86             6.7           3.1            4.7           1.5
76             6.8           2.8            4.8           1.4
71             6.1           2.8            4.0           1.3
134            6.1           2.6            5.6           1.4
51             6.4           3.2            4.5           1.5
73             6.1           2.8            4.7           1.2
54             6.5           2.8            4.6           1.5
63             6.1           2.9            4.7           1.4
37             4.9           3.1            1.5           0.1
78             6.0           2.9            4.5           1.5
90             5.5           2.6            4.4           1.2
45             4.8           3.0            1.4           0.3
16             5.4           3.9            1.3           0.4
121            5.6           2.8            4.9           2.0
66             5.6           3.0            4.5           1.5
24             4.8           3.4            1.9           0.2
8              4.4           2.9            1.4           0.2
126            6.2           2.8            4.8           1.8
22             4.6           3.6            1.0           0.2
44             5.1           3.8            1.9           0.4
97             6.2           2.9            4.3           1.3
93             5.0           2.3            3.3           1.0
26             5.0           3.4            1.6           0.4

In [15]:

#GaussianNB is specifically used when the features have continuous values.

from sklearn.naive_bayes import GaussianNB
model = GaussianNB()
model.fit(X_train, y_train)# fit fxn it is used to give traning to machine/model

prediction = model.predict(X_test)# predict fxn it is used to predict the values
print(prediction)
print(y_test)

['Iris-virginica' 'Iris-versicolor' 'Iris-setosa' 'Iris-virginica'
 'Iris-setosa' 'Iris-virginica' 'Iris-setosa' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-setosa'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-setosa' 'Iris-setosa'
 'Iris-virginica' 'Iris-versicolor' 'Iris-setosa' 'Iris-setosa'
 'Iris-virginica' 'Iris-setosa' 'Iris-setosa' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-setosa']
114     Iris-virginica
62     Iris-versicolor
33         Iris-setosa
107     Iris-virginica
7          Iris-setosa
100     Iris-virginica
40         Iris-setosa
86     Iris-versicolor
76     Iris-versicolor
71     Iris-versicolor
134     Iris-virginica
51     Iris-versicolor
73     Iris-versicolor
54     Iris-versicolor
63     Iris-versicolor
37         Iris-setosa
78     Iris-versicolor
90     Iris-versicolor
45         Iris-setosa
16         Iris-setosa
121     Iris-virginica
66     Iris-versi

In [7]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,prediction)

array([[11,  0,  0],
       [ 0, 13,  0],
       [ 0,  1,  5]], dtype=int64)

In [17]:
Totalcorrect=11+13+5
Total=30
accuracy =Totalcorrect/Total
accuracy


0.9666666666666667

In [16]:
from sklearn.metrics import accuracy_score

print(accuracy_score(y_test, prediction))



0.9666666666666667


In [5]:

print(metrics.confusion_matrix(y_test, prediction))
prediction


[[11  0  0]
 [ 0 13  0]
 [ 0  1  5]]


array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1,
       0, 0, 2, 0, 0, 1, 1, 0])