In [6]:
# import loabraries 
import numpy as np
import pandas as pd

# read the csv file 
df= pd.read_csv("textclass.csv")
df

Title  Label
0  I love India. India!      0
1         India is best      1
2    Germany beats both      1

In [7]:

# divide the dataset into 2 parts : dependent and independent  
y=df["Label"] # dependent
x=df["Title"] # indepenent 
x

0    I love India. India!
1           India is best
2      Germany beats both
Name: Title, dtype: object

In [8]:

# chek th einformation og independent varibale 
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Title   3 non-null      object
 1   Label   3 non-null      int64 
dtypes: int64(1), object(1)
memory usage: 176.0+ bytes


from sklearn.preprocessing import LabelEncoder

le=LabelEncoder()
x=le.fit_transform(x)
x

In [9]:
				  					  
###############################################################################################
# the words need to be encoded as integers or floating point values
#for use as input to a ML algorithm					  
				
#################################################################################################				
# Create bag of words
from sklearn.feature_extraction.text import CountVectorizer

count = CountVectorizer() 
"""CountVectorizer : vector is returned with a length of the entire vocabulary 
and an integer count for the number of times each word appeared in the document."""



count.fit(x)  


print(count.vocabulary_) 
#{'love': 6, 'india': 4, 'is': 5, 'best': 1, 'germany': 3, 'beats': 0, 'both': 2}



{'love': 6, 'india': 4, 'is': 5, 'best': 1, 'germany': 3, 'beats': 0, 'both': 2}


In [10]:

bag_of_words = count.fit_transform(x)
print(bag_of_words)


  (0, 6)	1
  (0, 4)	2
  (1, 4)	1
  (1, 5)	1
  (1, 1)	1
  (2, 3)	1
  (2, 0)	1
  (2, 2)	1


In [11]:
# Create feature matrix
X = bag_of_words.toarray()
print(X)
"""
#{'love': 6, 'india': 4, 'is': 5, 'best': 1, 'germany': 3, 'beats': 0, 'both': 2} 
# 7 columns because we have 7 seperate words in our dataset and 3 rows because we have 3 rows in dataset
[[0 0 0 0 2 0 1]  
 [0 1 0 0 1 1 0]
 [1 0 1 1 0 0 0]]
""" 


[[0 0 0 0 2 0 1]
 [0 1 0 0 1 1 0]
 [1 0 1 1 0 0 0]]


"\n#{'love': 6, 'india': 4, 'is': 5, 'best': 1, 'germany': 3, 'beats': 0, 'both': 2} \n# 7 columns because we have 7 seperate words in our dataset and 3 rows because we have 3 rows in dataset\n[[0 0 0 0 2 0 1]  \n [0 1 0 0 1 1 0]\n [1 0 1 1 0 0 0]]\n"

In [12]:


# Create multinomial naive Bayes object with prior probabilities of each class
from sklearn.naive_bayes import MultinomialNB
clf = MultinomialNB()

# Train model
model = clf.fit(X, y)

#{'love': 6, 'india': 4, 'is': 5, 'best': 1, 'germany': 3, 'beats': 0, 'both': 2}

xtest=np.array(["india is my country. I want to go germany, india"])
#xtest=np.array(["love germany"])
xtest=count.transform(xtest)  # only do trandform of xtest 
print(xtest)
xtest=xtest.toarray()
xtest


  (0, 3)	1
  (0, 4)	2
  (0, 5)	1


array([[0, 0, 0, 1, 2, 1, 0]], dtype=int64)

In [13]:

pred=clf.predict(xtest)

# Create new observation
#new_observation = [[0, 0, 0, 1, 0, 1, 0]]    
#new_observation = [[0, 0, 0, 1, 1, 1, 1]]    
#new_observation = [[0, 0, 1, 1, 1, 1, 1]]    


# Predict new observation's class
#pred = model.predict(new_observation)
print(pred)
					  
		
        

[1]
